  services:

      python_app: #do zrobienia
        build:
          dockerfile: Dockerfile #używany do budowy kontenera
        ports:
          - "5000:5000"
        volumes:
          - ./py_app:/py_app
        environment:
          - PYTHON_VERSION=3
        container_name: webapp
        depends_on:
            db:
                condition: service_healthy

      db: #chyba git
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: admin_db
          MYSQL_PASSWORD: qwerty # @małpa ma zakaz
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - '3306:3306'
        container_name: database
        healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
            timeout: 30s
            retries: 15
